PART = 2

.PHONY: oscillator poisson rnumber rwalk diffusion #set phony

oscillator: oscillator.py
	python3 oscillator.py --part=$(PART)

poisson: poisson.py
	python3 poisson.py --part=$(PART)

rnumber: rnumber.py
	python3 rnumber.py --part=$(PART)

rwalk: rwalk.py
        python3 rwalk.py --part=$(PART)

diffusion: diffusion.py
	python3 diffusion.py
